# -*- coding: utf-8 -*-
"""data_analysis and visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sgln_g3bNRV8zzv7y2ijDy-26xA0cDXi

**Week-4 Project : Analysing the Dataset and representing using Visualization**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset=pd.read_csv("/content/sales_data.csv")

dataset.head()

"""**Checking for missing values:**"""

dataset.isnull().sum()

"""No Missing values were present

**Total revenue overall the dataset**
"""

total_revenue=dataset["Total_Sales"].sum()
print(total_revenue)

"""**TOtla Revenue for each product sold**"""

revenue_per_product=dataset.groupby("Product")["Total_Sales"].sum().sort_values(ascending=False)
revenue_per_product

""" ** max revenue among the dataset**"""

dataset["Total_Sales"].max()

"""  **Avg revenue that each prodct get :**"""

dataset.groupby("Product")["Total_Sales"].mean()

"""**Total Revenue that each day can generate.**"""

dataset.groupby("Date")["Total_Sales"].sum()

"""Some Visualization techniques on this sales data

**Showing how much Revenue that each product generated regarding to the Dataset using Bar Graph**
"""

product_sales=(dataset.groupby("Product")["Total_Sales"].sum().sort_values(ascending=False))
product_sales

fig=plt.figure(figsize=(8,5))
plt.bar(product_sales.index,product_sales.values,
        width=0.5,
        color="yellow",
        edgecolor="black",
        linestyle="--",
        label="Total sales"
        )

plt.xlabel("Products")
plt.ylabel("Range of revenue")
plt.title("Product vs Total sales")
plt.legend(loc="upper right")
plt.show()

"""**Showing How much Revenue generated regarding to the region using Pie chart**"""

region_sales=dataset.groupby("Region")["Total_Sales"].sum()

fig=plt.figure(figsize=(8,6))
plt.pie(region_sales,
        autopct="%1.0f%%",
        explode=[0,0.1,0,0],
        shadow=True,
        startangle=90
        )
plt.legend(region_sales.index,title="region",loc="upper left")
plt.title("Percentage of Revenue in different Regions")
plt.show()

daily_sales=dataset.groupby("Date")["Total_Sales"].sum()

daily_sales

"""**Showing daily Revenue .like how much revenue is generating per each day using line plot**"""

plt.plot(daily_sales.index,
         daily_sales.values,
         linewidth=2,
         linestyle="-",
         label="Daily sales"
         )
plt.xlabel("days")
plt.ylabel("total_Sales")
plt.title("How sales vary over days")

plt.legend()
plt.show()

"""**Distribution of products based on overall dataset using Histogram**"""

plt.hist(dataset["Product"],
         label="no of products",
         color="orange",
         linewidth=2,
         linestyle="-",
         edgecolor="black")
plt.xlabel("Product")
plt.ylabel("No of Prodct sold")
plt.title("showing how many products were sold entire given dataset")
plt.legend()
plt.show()

